apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-svc
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: producer-svc
  template:
    metadata:
      labels:
        app: producer-svc
    spec:
      containers:
        - name: producer-svc
          image: kafka-practice/producer:v1
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: app-config
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: producer-svc
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: producer-svc
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
