// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: schemas/fraud_alert.proto

package schemas

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FraudAlert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertId       string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	RiskScore     float64                `protobuf:"fixed64,4,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudAlert) Reset() {
	*x = FraudAlert{}
	mi := &file_schemas_fraud_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudAlert) ProtoMessage() {}

func (x *FraudAlert) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_fraud_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudAlert.ProtoReflect.Descriptor instead.
func (*FraudAlert) Descriptor() ([]byte, []int) {
	return file_schemas_fraud_alert_proto_rawDescGZIP(), []int{0}
}

func (x *FraudAlert) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *FraudAlert) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *FraudAlert) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *FraudAlert) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *FraudAlert) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_schemas_fraud_alert_proto protoreflect.FileDescriptor

const file_schemas_fraud_alert_proto_rawDesc = "" +
	"\n" +
	"\x19schemas/fraud_alert.proto\x12\x0ekafka.practice\"\xa4\x01\n" +
	"\n" +
	"FraudAlert\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x04 \x01(\x01R\triskScore\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAtB2Z0github.com/0xRichardL/kafka-practice/pkg/schemasb\x06proto3"

var (
	file_schemas_fraud_alert_proto_rawDescOnce sync.Once
	file_schemas_fraud_alert_proto_rawDescData []byte
)

func file_schemas_fraud_alert_proto_rawDescGZIP() []byte {
	file_schemas_fraud_alert_proto_rawDescOnce.Do(func() {
		file_schemas_fraud_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemas_fraud_alert_proto_rawDesc), len(file_schemas_fraud_alert_proto_rawDesc)))
	})
	return file_schemas_fraud_alert_proto_rawDescData
}

var file_schemas_fraud_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schemas_fraud_alert_proto_goTypes = []any{
	(*FraudAlert)(nil), // 0: kafka.practice.FraudAlert
}
var file_schemas_fraud_alert_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schemas_fraud_alert_proto_init() }
func file_schemas_fraud_alert_proto_init() {
	if File_schemas_fraud_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemas_fraud_alert_proto_rawDesc), len(file_schemas_fraud_alert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schemas_fraud_alert_proto_goTypes,
		DependencyIndexes: file_schemas_fraud_alert_proto_depIdxs,
		MessageInfos:      file_schemas_fraud_alert_proto_msgTypes,
	}.Build()
	File_schemas_fraud_alert_proto = out.File
	file_schemas_fraud_alert_proto_goTypes = nil
	file_schemas_fraud_alert_proto_depIdxs = nil
}
